### ISSUE TITLE
Add Data Vault to Ethereum DIDs

### ISSUE THREAD

**Issue by miltonwg** [rsksmart/rif-identity-manager#23]
At this moment the Data Vault is not appearing when logging in with an Ethereum DID.

Would it be possible to support the main chain and at least one testnet (eg, Kovan)?

Example logging in with Argent using Eth mainnet, no data vault section:

<img width="1092" alt="Screen Shot 2020-12-04 at 18 44 35" src="https://user-images.githubusercontent.com/5920311/101217975-047d9a00-3661-11eb-8f3d-3b95807e5a6a.png">

**Comment by jessgusclark** [comment]
Reopening issue to add Ethereum testnets:

- [x] Mainnet
- [ ] Kovan
- [ ] Ropsten
- [ ] Goerli
- [ ] Rinkeby
