### ISSUE TITLE
Discussion: what to do if the user use a wallet that has not been tested for encryption

### ISSUE THREAD

**Issue by javiesses** [rsksmart/rif-identity-manager#48]
I think we should assume that if the wallet is not Metamask, we should not try to encrypt. Let's create an issue out of this

_Originally posted by @javiesses in https://github.com/rsksmart/rif-identity-manager/pull/44#discussion_r562116438_

**Comment by miltonwg** [comment]
Agree.
At this moment we should assume that and inform the user that the encryption feature is not enabled for any non-metamask wallet (same way we do with Nifty and WC).

**Comment by jessgusclark** [comment]
The best way to do this is given the provider: `(provider.isMetaMask && !provider.isNifty)`

Because Nifty wallet will return true for`isMetaMask`.

**Comment by jessgusclark** [comment]
I am going to close this as we are using an [asymmetric encryption method](https://github.com/rsksmart/rif-data-vault/blob/develop/modules/ipfs-cpinner-client/src/encryption-manager/asymmetric.ts) for non Metamask wallets.
